version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  test:
    docker:
      - image: 'cimg/node:20.11.0-browsers'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run:
          command: yarn
      - run:
          command: yarn test
workflows:
    sample:
      jobs:
        - test

